### ISSUE TITLE
where to find `targetClientId` for *config*?

### ISSUE THREAD

**Issue by matiishyn** [auth0-samples/auth0-s3-sample#5]
Hi.
I'm trying to runf this example and trying to paste my data into `congig.js`, but I'm confused with the last item: `targetClientId`. Where can I find it?
![image](https://cloud.githubusercontent.com/assets/3661065/14763009/661f265c-0989-11e6-956b-9dc5f519098a.png)

Please help me

**Comment by sandrinodimattia** [comment]
The target client ID can be the same as the Auth0 client ID if you just have a single application in Auth0.

**Comment by matiishyn** [comment]
yes, it works that way. Thanks @sandrinodimattia
